reviews:
  profile: assertive         
  high_level_summary: true   
  request_changes_workflow: true   
  auto_review:
    enabled: true
    drafts: false

  tools:
    # Java-focused analyzers
    checkstyle:
      enabled: true
      # optionally point to your config: config_path: "config/checkstyle/checkstyle.xml"
    spotbugs:
      enabled: true
    pmd:
      enabled: true

